apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f Docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: frontendimage
  name: frontendimage
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontendimage
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f Docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: frontendimage
    spec:
      containers:
        - image: frontendimage
          name: frontendimage
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /var/www/html
              name: frontendimage-claim0
      restartPolicy: Always
      volumes:
        - name: frontendimage-claim0
          persistentVolumeClaim:
            claimName: frontendimage-claim0
status: {}
